name: ML App CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python version
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          poetry install

      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV
          
      # Step 4: Run tests
      - name: Run tests
        run: poetry run pytest

      # Step 5: Train the model
      - name: Train model
        run: poetry run python src/train.py

      # Step 6: Build documentation
      - name: Build documentation
        run: poetry run make html --directory docs/

